
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-5pm-4
owner: ucsb-cs156-s23
repo_name: team02-s23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjc5MDY5OTY0","is_bot":false,"login":"zachmiller-ucsb","name":"Zach Miller"},"headRefName":"zach-create-rest-database","number":42,"title":"added entity and repository for restaurants","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-4/pull/42"},{"author":{"id":"MDQ6VXNlcjQ0NTMwNzM5","is_bot":false,"login":"SophiaWeiler","name":"Sophia Weiler"},"headRefName":"sophia-attractionsDatabaseTable","number":41,"title":"sw - edited attractions entities and repositories","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-4/pull/41"}]
