
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-5pm-4
owner: ucsb-cs156-s23
repo_name: team02-s23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjc5MDY5OTY0","is_bot":false,"login":"zachmiller-ucsb","name":"Zach Miller"},"headRefName":"zach-rest-controller-get-post1","number":50,"title":"zm - added restaurant controller+  working tests ","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-4/pull/50"},{"author":{"id":"MDQ6VXNlcjcyMjM2OTY4","is_bot":false,"login":"mike-k999","name":""},"headRefName":"Michael-transportController","number":49,"title":"Michael transport controller","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-4/pull/49"},{"author":{"id":"MDQ6VXNlcjc5MDY5OTY0","is_bot":false,"login":"zachmiller-ucsb","name":"Zach Miller"},"headRefName":"zach-rest-controller-get-post","number":48,"title":"zm-added restaurant controller + tests for get and post","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-4/pull/48"}]
